import { CONFIG, SEASONS } from './config.js';
import { ITEMS, LAMPS, ANCHORS, getVisibleItems } from './layout.js';
import { drawScene, hitTest } from './scene.js';
import { loadPreferences, savePreferences, resolvePreferences, loadWorld, advanceWorld } from './store.js';
import { NavigationController } from './navigation.js';
import { LifeDirector } from './life.js';
import { PetWorld } from './pets.js';
import { Environment } from './environment.js';
import { AudioSystem } from './audio.js';
import { loadLetterOverrides } from './letters.js';
import { now, dayNumber } from './time.js';
import { STORY } from './content/index.js';

const $=id=>document.getElementById(id),canvas=$('house'),dialog=$('details'),callCard=$('call-card');let preferences=loadPreferences(),world=loadWorld(),nav,life,pets,environment,audio,lastFrame=0,hintTimer;
function runtime(){const petState=pets.snapshots(),lifeState=life.snapshot(),time=now();return {actor:{...nav.snapshot(),pose:lifeState.pose,held:lifeState.held,motion:lifeState.motion,reaction:lifeState.reaction,outfit:world.outfit},life:lifeState,pets:petState,world,weather:environment.weather,time};}
function note(text){$('item-hint').textContent=text;$('item-hint').classList.add('visible');clearTimeout(hintTimer);hintTimer=setTimeout(()=>$('item-hint').classList.remove('visible'),2200);}
function stateText(){const current=life.snapshot();$('lyrics').hidden=!current.lyric;$('lyrics').textContent=current.lyric||'';}
function render(){const state=resolvePreferences(preferences,now());drawScene(canvas,state,runtime());stateText();$('scene-caption').textContent=SEASONS[state.season]+'日 · '+(state.theme==='night'?'灯火可亲':'阳光正好');updateCallCard();}
function element(tag,text,className){const el=document.createElement(tag);if(text!==undefined&&text!==null)el.textContent=text;if(className)el.className=className;return el;}
function setDialog(title,kicker='ROOM OBJECTS'){const content=$('details-content');$('details-kicker').textContent=kicker;content.replaceChildren(element('h2',title));content.firstChild.id='details-title';if(!dialog.open)dialog.showModal();return content;}
function showLetter(key){const uploaded=loadLetterOverrides()[key],letter=uploaded||STORY.letters[key],content=setDialog(letter.title,uploaded?'YOUR LETTER':'LETTERS TO MOMO');content.append(element('p',letter.from+' → '+letter.to,'room-tag'));letter.paragraphs.forEach(text=>content.append(element('p',text,'letter-body')));}
function drawComputerScreen(screen,mode,t){const ctx=screen.getContext('2d'),w=400,h=250,time=now(),qixi=time.year===2026&&time.month===8&&time.day===19;ctx.imageSmoothingEnabled=false;ctx.fillStyle='#07131d';ctx.fillRect(0,0,w,h);ctx.fillStyle=qixi?'#4c2943':'#193348';ctx.fillRect(15,14,w-30,h-28);if(mode==='coding'){ctx.fillStyle='#8dd3b1';ctx.font='14px monospace';for(let i=0;i<11;i++)ctx.fillText((i+1)+'  '+['const day = slow;','while (home) {','  makeTea();','  pet(cat);','  listen(rain);','}','// ordinary is enough'][i%7],30,42+i*17);}else if(mode==='chat'){ctx.fillStyle='#d8e6dd';ctx.font='17px sans-serif';ctx.fillText(qixi?'MOMO · 七夕快乐':'MOMO',30,45);for(let i=0;i<5;i++){ctx.fillStyle=i%2?'#526c78':'#496c58';ctx.fillRect(i%2?135:32,65+i*31,220,22);}if(qixi){ctx.fillStyle='#f39bc2';for(let i=0;i<14;i++)ctx.fillText('♥',25+(i*47)%350,32+(i*31)%190);}ctx.fillStyle='#e8d698';ctx.fillText('正在输入…',250,226);}else if(mode==='video'||mode==='game'){ctx.fillStyle='#769b6d';ctx.fillRect(30,45,340,165);ctx.fillStyle='#e89a4a';ctx.fillRect(80+(t/20)%230,155,34,22);ctx.fillStyle='#283d58';ctx.fillRect(280-(t/28)%170,95,36,26);}else if(mode==='art'){for(let y=30;y<220;y+=12)for(let x=25;x<375;x+=12){ctx.fillStyle=['#e8b775','#769b6d','#6c8fab','#b87979'][(x+y)/12%4|0];ctx.fillRect(x,y,10,10);}}else{ctx.fillStyle='#d4c792';for(let i=0;i<18;i++)ctx.fillRect(30+(i*31)%330,35+(i*47)%170,22,12);ctx.fillStyle='#f1ead1';ctx.font='18px sans-serif';ctx.fillText('今天也稍微休息一下',78,224);}}
const chatBackground=new Image();chatBackground.src='../assets/chat-bg.jpg';
function drawComputerScreenRich(screen,mode,t){const ctx=screen.getContext('2d'),w=400,h=250;ctx.imageSmoothingEnabled=false;ctx.fillStyle='#101522';ctx.fillRect(0,0,w,h);ctx.fillStyle='#20293a';ctx.fillRect(0,0,w,20);ctx.fillStyle='#b9d5ff';ctx.font='12px monospace';ctx.fillText(mode==='chat'?'MOMO':'PIXEL ROOM',12,14);ctx.fillStyle='#4ae07a';ctx.fillRect(w-25,9,6,6);
  if(mode==='coding'){ctx.fillStyle='#161c2a';ctx.fillRect(0,20,72,h-20);ctx.fillStyle='#101522';ctx.fillRect(72,20,w-72,h-20);ctx.fillStyle='#9fb3c8';ctx.font='11px Consolas,monospace';ctx.fillText('pathfinder.py  ×',86,35);const lines=['from collections import deque','def walk(home):','    while home.is_alive():','        make_tea()','        pet(cat)','        listen(rain)','    return ordinary'];for(let i=0;i<lines.length;i++){ctx.fillStyle=i===1||i===2?'#c792ea':'#d6deeb';ctx.fillText(String(i+1).padStart(2,'0'),78,55+i*22);ctx.fillText(lines[i],100,55+i*22);}ctx.fillStyle='#17324d';ctx.fillRect(72,h-22,w-72,22);ctx.fillStyle='#b9d8f2';ctx.font='10px monospace';ctx.fillText('Python 3.12   UTF-8   typing',84,h-8);}
  else if(mode==='video'){ctx.fillStyle='#6f8296';ctx.fillRect(0,20,w,140);ctx.fillStyle='#d9c49d';ctx.fillRect(18,40,70,60);ctx.fillStyle='#89b8d0';ctx.fillRect(24,46,58,48);ctx.fillStyle='#596c76';ctx.fillRect(w-95,95,75,42);const run=Math.floor((t*28)%(w-100)),cx=10+run,gy=158;ctx.fillStyle='#64788d';ctx.fillRect(cx,gy-20,24,12);ctx.fillRect(cx+16,gy-28,12,12);ctx.fillStyle='#d8d5c9';ctx.fillRect(cx+19,gy-24,8,6);ctx.fillStyle='#9b6a54';ctx.fillRect(cx+55,gy-12,18,10);ctx.fillStyle='#e6bd49';ctx.fillRect(cx+73,gy-10,14,8);ctx.fillStyle='#ff5a7a';ctx.fillRect(12,h-20,w-24,3);ctx.fillStyle='#eef3ff';ctx.font='10px sans-serif';ctx.fillText('CAT & MOUSE · EP. 07',14,h-27);}
  else if(mode==='chat'){if(chatBackground.complete&&chatBackground.naturalWidth)ctx.drawImage(chatBackground,0,20,w,h-20);else{ctx.fillStyle='#5f4b68';ctx.fillRect(0,20,w,h-20);}ctx.fillStyle='rgba(7,12,24,.52)';ctx.fillRect(0,20,w,h-20);const qixi=now().year===2026&&now().month===8&&now().day===19;if(qixi){ctx.fillStyle='#ff91ad';for(let i=0;i<8;i++)ctx.fillText('♥',20+(i*53)%360,35+((i*29+Math.floor(t*5))%165));}ctx.fillStyle='#8fa2ba';ctx.font='11px sans-serif';ctx.fillText(qixi?'七夕限定 · 今夜星河':'在线 · 刚刚',82,35);const messages=qixi?['七夕节快乐','你也七夕节快乐','我们在一起可以吗？']:['日落和日出不一样呀','怎么不一样','那我们等着星星落下，太阳升起'];for(let i=0;i<messages.length;i++){const mine=i===1, y=55+i*42;ctx.fillStyle=mine?'rgba(51,91,68,.94)':'rgba(34,48,77,.94)';ctx.fillRect(mine?210:18,y,mine?165:190,25);ctx.fillStyle='#f0f4ff';ctx.fillText(messages[i],mine?220:28,y+16);}ctx.fillStyle='#ffd5df';ctx.fillText('对方正在输入'+'.'.repeat(1+Math.floor(t*3)%3),18,190);ctx.fillStyle='rgba(15,22,38,.9)';ctx.fillRect(10,h-27,w-20,16);ctx.fillStyle='#8795aa';ctx.fillText('输入消息…',18,h-16);}
  else if(mode==='slacking'||mode==='game'){ctx.fillStyle='#1a281d';ctx.fillRect(0,20,w,h-20);ctx.fillStyle='#f5db67';ctx.font='10px monospace';ctx.fillText('1P  004280      HI  012600      LIFE × 3',12,34);for(let i=0;i<6;i++){const x=28+i*58,y=62+(i*23)%95;ctx.fillStyle='#8e4934';ctx.fillRect(x,y,30,12);ctx.fillStyle='#285b77';ctx.fillRect(190,45,20,100);}const tank=(x,y,c)=>{ctx.fillStyle='#27302a';ctx.fillRect(x,y,14,14);ctx.fillStyle=c;ctx.fillRect(x+3,y+3,8,8);ctx.fillRect(x+6,y-6,3,9);};tank(215+Math.sin(t*1.7)*24,190,'#6fcf78');tank(35+(t*18)%300,45,'#e05d50');tank(320-(t*11)%260,90,'#e7b64d');ctx.fillStyle='#f6f1b5';ctx.fillRect(221,145-(t*45%90),3,7);}
  else {ctx.fillStyle='#1b2030';ctx.fillRect(0,20,w,h-20);for(let y=35;y<220;y+=14)for(let x=18;x<390;x+=14){ctx.fillStyle=['#e8b775','#769b6d','#6c8fab','#b87979'][(x+y)/14%4|0];ctx.fillRect(x,y,11,11);}ctx.fillStyle='#f1ead1';ctx.font='13px sans-serif';ctx.fillText('今天也稍微休息一下',126,235);}}
function openComputer(){const modes=[['coding','写代码'],['video','看视频'],['chat','MOMO 聊天'],['slacking','摸鱼'],['art','画画'],['game','打游戏']],content=setDialog('电脑屏幕','DESKTOP');let index=Math.max(0,modes.findIndex(([id])=>id===life.snapshot().activity)),mode=modes[index][0],screen=element('canvas',null,'computer-screen');screen.width=400;screen.height=250;content.append(screen);const caption=element('p','','detail-copy'),button=element('button','换台','inventory-button');content.append(caption,button);let frame=0;const draw=()=>{if(!dialog.open||!screen.isConnected)return;drawComputerScreenRich(screen,mode,frame++/60);requestAnimationFrame(draw);};button.addEventListener('click',()=>{index=(index+1)%modes.length;mode=modes[index][0];caption.textContent='当前屏幕：'+modes[index][1];audio.chime();});caption.textContent='当前屏幕：'+modes[index][1];draw();}
function showCall(){const call=life.snapshot().call||STORY.calls[dayNumber()%STORY.calls.length],content=setDialog('今晚的话题 · '+call.title,'MOMO CALL · DAY '+(dayNumber()%100+1)),log=element('div',null,'call-log');for(const line of call.lines){const row=element('p',(line.speaker||'MOMO')+'：'+line.text,'call-line '+((line.speaker||'')==='我'?'me':'momo'));log.append(row);}content.append(log);}
function showLetters(){const content=setDialog('书架上的两封信','LETTERS TO MOMO'),list=element('div',null,'content-list');content.append(element('p','点击信封阅读完整正文。','detail-copy'));for(const key of ['toMomo','fromMomo']){const button=element('button',STORY.letters[key].title);button.addEventListener('click',()=>showLetter(key));list.append(button);}content.append(list);}
const LAMP_FRIGHT_WINDOW=5,LAMP_FRIGHT_COOLDOWN=30,lampToggles=[];let lampFrightAt=-Infinity;
function toggleLamp(lamp){const resolved=resolvePreferences(preferences,now());preferences.lampMode='manual';preferences.lamps=[...resolved.lamps];preferences.lamps[lamp.index]=!preferences.lamps[lamp.index];savePreferences(preferences);audio.chime(520);render();const at=Date.now()/1000;lampToggles.push(at);while(lampToggles.length&&at-lampToggles[0]>LAMP_FRIGHT_WINDOW)lampToggles.shift();if(lampToggles.length>=3&&at-lampFrightAt>LAMP_FRIGHT_COOLDOWN){lampFrightAt=at;lampToggles.length=0;pets.frighten();life.react('lookup');note('闪得太快了，猫被吓跑了。');}}
function startGuitar(){const result=life.startGuitar();if(result==='ok')return;note(result==='busy'?'正在弹《'+(life.snapshot().song?.title||'')+'》。':result==='sleep'?'小人睡着了，明天再弹吧。':'正在和 MOMO 通话，等一会儿吧。');}
function startChange(){const result=life.startChange();if(result==='ok')return;note(result==='busy'?'已经在换衣服了。':result==='sleep'?'小人睡着了，明天再换吧。':result==='call'?'正在和 MOMO 通话，等一会儿吧。':'晚上休闲的时候再来换衣服吧。');}
function mealTip(){const current=life.snapshot();if(current.meal)return note('桌上是 '+current.meal.name+'。');if(current.snack)return note('手边是 '+current.snack.name+'。');note('现在没有做饭，餐桌是空的。');}
function doorTip(){note('木门还锁着。天气好的傍晚，小人会自己出去荡秋千。');}
function nameTip(hit){note('🧸 '+(hit.tip||hit.label));}
function hoverText(hit){if(hit.action==='computer')return '电脑';if(hit.action==='letters')return '书架 · 两封信';if(hit.action==='guitar')return '木吉他';if(hit.action==='wardrobe')return '衣柜';if(hit.action==='door')return '户外木门';return hit.tip||hit.label;}
function updateCallCard(){const current=life.snapshot();if(!current.call){callCard.hidden=true;return;}const line=current.callLine||{speaker:'MOMO',text:'…'};callCard.hidden=false;callCard.querySelector('.call-card-title').textContent='☎ MOMO 来电 · '+current.call.title;callCard.querySelector('.call-card-speaker').textContent=line.speaker;callCard.querySelector('.call-card-text').textContent=line.text;}
function interactEntity(kind){audio.interact(kind);if(kind==='human'){life.react();return;}pets.interact(kind,nav.snapshot());}
function coordinates(event){const r=canvas.getBoundingClientRect();return{x:(event.clientX-r.left)/r.width*CONFIG.width,y:(event.clientY-r.top)/r.height*CONFIG.height};}
canvas.addEventListener('click',event=>{const state=resolvePreferences(preferences,now()),hit=hitTest(coordinates(event).x,coordinates(event).y,state,runtime());if(!hit)return;if(hit.type==='entity')return interactEntity(hit.entity);if(hit.type==='lamp')return toggleLamp(hit);if(hit.action==='computer')return openComputer();if(hit.action==='letters')return showLetters();if(hit.action==='guitar')return startGuitar();if(hit.action==='wardrobe')return startChange();if(hit.action==='meal')return mealTip();if(hit.action==='door')return doorTip();if(hit.action==='name')return nameTip(hit);});
canvas.addEventListener('pointermove',event=>{if(event.pointerType==='touch')return;const state=resolvePreferences(preferences,now()),p=coordinates(event),hit=hitTest(p.x,p.y,state,runtime());canvas.style.cursor=hit?'pointer':'default';if(hit){$('item-hint').textContent=hoverText(hit);$('item-hint').classList.add('visible');}else $('item-hint').classList.remove('visible');});canvas.addEventListener('pointerleave',()=>$('item-hint').classList.remove('visible'));
callCard.addEventListener('click',showCall);
function openMenu(){const content=setDialog('小屋菜单','PIXEL ROOM'),list=element('div',null,'content-list');for(const [label,action] of [[preferences.sound?'关闭声音':'开启声音',async()=>{preferences.sound=!preferences.sound;savePreferences(preferences);audio.setPreferences(preferences);if(preferences.sound)await audio.enable();openMenu();}]]){const button=element('button',label);button.addEventListener('click',action);list.append(button);}const link=element('a','小屋设置 →','inventory-button');link.href='../setting';list.append(link);content.append(list);}
$('house-menu').addEventListener('click',openMenu);
$('close-details').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>render());dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}});
window.addEventListener('storage',event=>{if(event.key===CONFIG.storageKey){preferences=loadPreferences();audio.setPreferences(preferences);}if(event.key===CONFIG.worldStorageKey){world=loadWorld();life.world=world;pets.cat.world=world;pets.dog.world=world;}render();});
function frame(timestamp){const dt=Math.min(.05,lastFrame?(timestamp-lastFrame)/1000:0);lastFrame=timestamp;const lifeState=life.snapshot();nav.update(dt);life.update(dt);pets.update(dt,nav.snapshot(),lifeState);environment.update();audio.update(environment.weather,now(),lifeState);if(Math.floor(timestamp/60000)!==Math.floor((timestamp-dt*1000)/60000))advanceWorld(world);render();requestAnimationFrame(frame);}
try{nav=new NavigationController();life=new LifeDirector(nav,world);pets=new PetWorld(world);environment=new Environment();audio=new AudioSystem(preferences);render();$('loading').hidden=true;requestAnimationFrame(frame);window.PortraitPreview=Object.freeze({stage:CONFIG.stage,get state(){return structuredClone(preferences);},get actor(){return nav.snapshot();},get life(){return life.snapshot();},get pets(){return pets.snapshots();},get diagnostics(){return {timer:life.timer,index:life.index,catTimer:pets.cat.timer,dogTimer:pets.dog.timer};},get world(){return structuredClone(world);},get items(){return structuredClone(ITEMS);},get anchors(){return structuredClone(ANCHORS);},get visible(){return getVisibleItems(resolvePreferences(preferences),world).map(i=>i.id);}});}catch(error){$('loading').textContent='小屋暂时没有加载成功，请刷新后再试。';$('loading').classList.add('error');console.error(error);}
function updateClock(){const t=now();$('clock').textContent='北京 '+String(t.hour).padStart(2,'0')+':'+String(t.min).padStart(2,'0');}updateClock();setInterval(updateClock,1000);
